print("Enter your name:")
name = input()
print("mother's name:")
name2 = input()
print("father's name:")
name3 = input()
print("Enter your age:")
age = input()
print("Enter your school name:")
school = input()
print ('thanks'+"\n"+name+"\n"+age +"\n"+school)
